---
version: 2.1

jobs:
    build_and_test: # this can be any name you choose
        docker:
            - image: circleci/python:3.10
        steps:
            - checkout
            - run:
                  - pip install -r requirements/dev-requirements.txt
                  - python -m pytest -m all

workflows:
    test_my_app:
        jobs:
            - build_and_test
