---
version: 2.1

jobs:
    build_and_test: # this can be any name you choose
        docker:
            - image: circleci/python:3.10
        steps:
            - checkout
            - python/install-packages:
                  pkg-manager: pip
                  pip-dependency-file: requirements/dev-requirements.txt
            - run:
                  name: Run tests
                  command: python -m pytest -m all - .

workflows:
    test_my_app:
        jobs:
            - build_and_test
